In [2]:
import numpy as np
import random 

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [20]:
array_act1 = np.random.randint(10, 100, (50))
array_act1

array([59, 30, 55, 91, 67, 83, 42, 92, 99, 10, 49, 28, 24, 10, 29, 73, 29,
       80, 44, 76, 75, 21, 35, 99, 38, 73, 26, 96, 78, 95, 87, 92, 98, 53,
       80, 19, 99, 90, 17, 77, 32, 63, 37, 49, 43, 47, 74, 35, 17, 36])

In [21]:
array_act1[array_act1 %5 == 0]

array([30, 55, 10, 10, 80, 75, 35, 95, 80, 90, 35])

In [22]:
multiplos = array_act1[::5] #seleccionar de 5 en 5
multiplos

array([59, 83, 49, 73, 75, 73, 87, 19, 32, 47])

2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [26]:
array_act2 = np.random.randint(1,21, (30))
array_act2


array([ 3, 14, 20,  2,  4,  5,  1, 16, 19,  8, 11,  5,  8,  3,  1, 20,  8,
       14, 20, 12,  7,  5, 11,  1, 17, 10,  7,  1,  2, 13])

In [37]:
impares = array_act2[1::2]
impares

array([14,  2,  5, 16,  8,  5,  3, 20, 14, 12,  5,  1, 10,  1, 13])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [39]:
array_act3 = np.random.rand(4,6)
array_act3

array([[0.17263709, 0.08505418, 0.96942337, 0.49634077, 0.81624494,
        0.00788883],
       [0.3251549 , 0.9174429 , 0.11199121, 0.46315781, 0.68466699,
        0.6575703 ],
       [0.8221198 , 0.34365639, 0.96278627, 0.19447133, 0.95325758,
        0.99357877],
       [0.91207589, 0.36336497, 0.33826739, 0.94707614, 0.05839751,
        0.10309013]])

In [42]:
array_act3 = np.round(array_act3, 2)
array_act3

array([[0.17, 0.09, 0.97, 0.5 , 0.82, 0.01],
       [0.33, 0.92, 0.11, 0.46, 0.68, 0.66],
       [0.82, 0.34, 0.96, 0.19, 0.95, 0.99],
       [0.91, 0.36, 0.34, 0.95, 0.06, 0.1 ]])

In [44]:
ultima_fila = array_act3[-1]
ultima_fila

array([0.91, 0.36, 0.34, 0.95, 0.06, 0.1 ])

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [47]:
array_3d = np.random.rand(2, 3 ,5)
array_3d

array([[[0.93704766, 0.16335667, 0.73638065, 0.89198071, 0.8412699 ],
        [0.35230032, 0.9586663 , 0.79034234, 0.50589389, 0.84939618],
        [0.11945964, 0.76980108, 0.2776314 , 0.63450318, 0.70077011]],

       [[0.1596423 , 0.21337765, 0.16153185, 0.95989047, 0.31359884],
        [0.70669478, 0.33128042, 0.62603471, 0.43375484, 0.26483952],
        [0.98630675, 0.22540277, 0.47227407, 0.19534855, 0.6712418 ]]])

In [48]:
array_3d = np.round(array_3d, 1)
array_3d

array([[[0.9, 0.2, 0.7, 0.9, 0.8],
        [0.4, 1. , 0.8, 0.5, 0.8],
        [0.1, 0.8, 0.3, 0.6, 0.7]],

       [[0.2, 0.2, 0.2, 1. , 0.3],
        [0.7, 0.3, 0.6, 0.4, 0.3],
        [1. , 0.2, 0.5, 0.2, 0.7]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [ ]:
array_vacio = np.empty((2, 3, 5)) #¿por qué es vacío si lo imprimimos con números?
array_vacio

array([[[0.9, 0.2, 0.7, 0.9, 0.8],
        [0.4, 1. , 0.8, 0.5, 0.8],
        [0.1, 0.8, 0.3, 0.6, 0.7]],

       [[0.2, 0.2, 0.2, 1. , 0.3],
        [0.7, 0.3, 0.6, 0.4, 0.3],
        [1. , 0.2, 0.5, 0.2, 0.7]]])

In [ ]:
media = np.mean(array_3d) #aqui estamos creando la variable con la media del ejer anterior
cualquiera = np.where(array_vacio == media, 'A', array_vacio) #el último array_vacio después de A es por si no lo encuentra que deje ese array vacio
cualquiera

array([[['0.9', '0.2', '0.7', '0.9', '0.8'],
        ['0.4', '1.0', '0.8', '0.5', '0.8'],
        ['0.1', '0.8', '0.3', '0.6', '0.7']],

       [['0.2', '0.2', '0.2', '1.0', '0.3'],
        ['0.7', '0.3', '0.6', '0.4', '0.3'],
        ['1.0', '0.2', '0.5', '0.2', '0.7']]], dtype='<U32')

In [57]:
media

0.5433333333333332

In [61]:
cualquiera = np.where(array_vacio > media, 'B', array_vacio)
cualquiera

array([[['B', '0.2', 'B', 'B', 'B'],
        ['0.4', 'B', 'B', '0.5', 'B'],
        ['0.1', 'B', '0.3', 'B', 'B']],

       [['0.2', '0.2', '0.2', 'B', '0.3'],
        ['B', '0.3', 'B', '0.4', '0.3'],
        ['B', '0.2', '0.5', '0.2', 'B']]], dtype='<U32')

In [62]:
cualquiera = np.where(array_vacio < media, 'C', array_vacio)
cualquiera

array([[['0.9', 'C', '0.7', '0.9', '0.8'],
        ['C', '1.0', '0.8', 'C', '0.8'],
        ['C', '0.8', 'C', '0.6', '0.7']],

       [['C', 'C', 'C', '1.0', 'C'],
        ['0.7', 'C', '0.6', 'C', 'C'],
        ['1.0', 'C', 'C', 'C', '0.7']]], dtype='<U32')

In [ ]:
maximo = np.max(array_3d)
cualquiera = np.where(array_vacio == maximo, 'D', array_vacio)
cualquiera

array([[['0.9', '0.2', '0.7', '0.9', '0.8'],
        ['0.4', '1.0', '0.8', '0.5', '0.8'],
        ['E', '0.8', '0.3', '0.6', '0.7']],

       [['0.2', '0.2', '0.2', '1.0', '0.3'],
        ['0.7', '0.3', '0.6', '0.4', '0.3'],
        ['1.0', '0.2', '0.5', '0.2', '0.7']]], dtype='<U32')

In [68]:
minimo = np.min(array_3d)
cualquiera = np.where(array_vacio == minimo, 'E', array_vacio)
cualquiera

array([[['0.9', '0.2', '0.7', '0.9', '0.8'],
        ['0.4', '1.0', '0.8', '0.5', '0.8'],
        ['E', '0.8', '0.3', '0.6', '0.7']],

       [['0.2', '0.2', '0.2', '1.0', '0.3'],
        ['0.7', '0.3', '0.6', '0.4', '0.3'],
        ['1.0', '0.2', '0.5', '0.2', '0.7']]], dtype='<U32')

In [ ]:
#sale bien pero falta juntarlo que es como pone en el ejemplo

In [80]:
cualquiera1 = np.where(array_vacio == media, 'A', array_vacio)
cualquiera2 = np.where(array_vacio > media, 'B', array_vacio)
cualquiera3 = np.where(array_vacio < media, 'C', array_vacio)
cualquiera4 = np.where(array_vacio == maximo, 'D', array_vacio)
cualquiera5 = np.where(array_vacio == minimo, 'E', array_vacio)

In [81]:
todo_junto1 = [(cualquiera1)&(cualquiera2)&(cualquiera3)&(cualquiera4)&(cualquiera5)]

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
todo_junto = [(cualquiera1)|(cualquiera2)|(cualquiera3)|(cualquiera4)|(cualquiera5)]

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

: 